### ISSUE TITLE
Can't find where the current wallpaper is stored

### ISSUE THREAD

**Issue by brighamdent** [0bCdian/Waypaper-Engine#10]
I need the current wallpaper to be able to dynamically update other things in my rice.

**Comment by 0bCdian** [comment]
I'm currently working on this alongside other major features, I will release a new major version soon. I was thinking on having a json file on the .cache folder alongside a new CLI command query that would basically be a better version of swww query which you can use right now but it's not formatted, so you'll have to do some string manipulation to get the info you want. More feedback on what exactly you want would be appreciated though, cheers!

 btw  if you're interested you can see how development is going here 
 
 https://github.com/0bCdian/Waypaper-Engine/issues/7#issuecomment-2050289649

**Comment by brighamdent** [comment]
I was also curious I I use a script to pass the wall papers to rofi but it only works if I manually change the wallpaper. It doesn't work on a slide show. Great app btw

**Comment by 0bCdian** [comment]
Hi! I already released the new version, read the release notes because there is a breaking change regarding scripts, instead of a command flag, its now a directory in which you put the script bash files, and they get executed on each image set :)
