### ISSUE TITLE
Unable to install. Failure during build

### ISSUE THREAD

**Issue by dimitrisfasoulas** [0bCdian/Waypaper-Engine#12]
This is the output of `yay -S waypaper-engine`
```
AUR Explicit (1): waypaper-engine-2.0.0-1
:: PKGBUILD up to date, skipping download: waypaper-engine
  1 waypaper-engine                  (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
  1 waypaper-engine                  (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
==> Making package: waypaper-engine 2.0.0-1 (Tue 07 May 2024 03:53:32 PM CEST)
==> Retrieving sources...
  -> Found Waypaper-Engine-2.0.0.tar.gz
==> WARNING: Skipping verification of source file PGP signatures.
==> Validating source files with md5sums...
    Waypaper-Engine-2.0.0.tar.gz ... Skipped
:: (1/1) Parsing SRCINFO: waypaper-engine
==> Making package: waypaper-engine 2.0.0-1 (Tue 07 May 2024 03:53:32 PM CEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found Waypaper-Engine-2.0.0.tar.gz
==> Validating source files with md5sums...
    Waypaper-Engine-2.0.0.tar.gz ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting Waypaper-Engine-2.0.0.tar.gz with bsdtar
==> Sources are ready.
==> Making package: waypaper-engine 2.0.0-1 (Tue 07 May 2024 03:53:33 PM CEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Removing existing $pkgdir/ directory...
==> Starting build()...
wpe-daemon: no process found
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: waypaper-engine-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
waypaper-engine - exit status 4
```

I had the previous version installed but had the same issue on update. Used pacman -R to remove previous version but issue persists.

If more logs are required let me know and I'll provide them

**Comment by Gl00ria** [comment]
Same issue here

**Comment by 0bCdian** [comment]
uninstall with `yay -Rns waypaper-engine waypaper-engine-debug` and try again, I suspect this is because I added a line in the build function which tries to kill the wpe-daemon proccess before building, but on my machine it didn't cause problems, anyway, I already changed it back, try to install it again and let me know, sorry for the inconvenience :(

**Comment by 0bCdian** [comment]
I created a new -git package in the aur, for those interested to always have the latest git changes! Also for the manual installation I simplified the process a bit further, please let me know if you encounter any other bugs.

**Comment by Gl00ria** [comment]
Fantastic work, I've been eying the project since day 0. I was trying to push it to its limit, so I pushed around 500 pic all at once to see if it crashes or not, BUT surprised me (it was super fast + never crashed), lovely.

### Suggestion:
How about adding `waypaper-engine-bin` pkg?

**Comment by 0bCdian** [comment]
I'll get to the binary package soon enough, maybe tomorrow if I have the time!

**Comment by 0bCdian** [comment]
I'll be closing this issue now!
