### ISSUE TITLE
Please share the sway config

### ISSUE THREAD

**Issue by BPOH** [0bCdian/Waypaper-Engine#16]
Very beautiful desktop design, please share your config, and what additional programs and themes do you use? I would be very grateful!

**Comment by 0bCdian** [comment]
Well, I'll close this issue since is not relevant to the project, and my dotfiles are here https://github.com/0bCdian/Hyprland_dotfiles

**Comment by BPOH** [comment]
Thank you so much! Please pardon the off-topic
