### ISSUE TITLE
Unable to select display in sway

### ISSUE THREAD

**Issue by aarRJaay** [0bCdian/Waypaper-Engine#20]
The 'select display' button doesn't give a box to select my display -  running waypaper-engine info produces 

{
  "action": "error",
  "error": {
    "error": {}
  }
}

I'm able to manually select a wallpaper and display it - however, I'd really like to create a playlist and show randomly changing wallpaper please.

Thank you

RJ

**Comment by 0bCdian** [comment]
do you have wlr-randr installed in your system? Looks like that may be the culprit if you're running the binary alone. Upon further checking the issue was on my part in the aur packages, for not specifying the wlr-randr package as a dependency (I used to package the binary directly but since some versions back im using the system defaults, and forgot to add the dependency in the aur package). I will update those shortly but in the meantime, install wlr-randr and it should fix your issue. Sorry for the inconveniences!

**Comment by aarRJaay** [comment]
Thank you - that worked perfectly!!! I LOVE that I don't have to write a shell script to get my wallpapers - this is EXACTLY the application I've been looking for.

----------------------------"No trees were killed to send this message, but a large number of electrons were terribly inconvenienced." - Neil deGrasse Tyson

**Comment by 0bCdian** [comment]
I already fixed the aur packages, so I will be closing this issue. I'm glad you liked it! Any other feedback would be appreciated, feel free to open an issue if you need anything else!

**Comment by ChristopherAckerman** [comment]
I just installed waypaper-engine, and I think I'm having the same issue. The error message is

`Error occurred in handler for 'getMonitors': Error: Could not query swww
    at getMonitors (/opt/waypaper-engine/resources/app/dist-electron/main.js:10657:11)
    at async /opt/waypaper-engine/resources/app/dist-electron/main.js:11805:10
    at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:82855)`

**Comment by 0bCdian** [comment]
> I just installed waypaper-engine, and I think I'm having the same issue. The error message is
> 
> `Error occurred in handler for 'getMonitors': Error: Could not query swww at getMonitors (/opt/waypaper-engine/resources/app/dist-electron/main.js:10657:11) at async /opt/waypaper-engine/resources/app/dist-electron/main.js:11805:10 at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:82855)`

Could you open a new issue? I'm gonna need some info:

- Which version of waypaper engine are you using.
- Which distro are you using.
- Where is the error happening?.

I'll get to it asap.
