### ISSUE TITLE
Waypaper Daemon crashing when running the application

### ISSUE THREAD

**Issue by aarRJaay** [0bCdian/Waypaper-Engine#22]
I don't seem to be able to run it with --logs but I can run it with info

> waypaper-engine info                                                               
 socat[96814] E connect(, AF=1 "/tmp/waypaper_engine_daemon.sock", 34): No such file or directory

This is what happens when I run it.  It seems to have started since I tried running it not connected to a monitor (I usually run in clamshell mode) - Wonder if it got confused somewhere and I need to clear something out.

> waypaper-engine run                                                                    
swww is installed in the system
Error: Failed to establish connection to waypaper daemon.
    at testConnection (/opt/waypaper-engine/resources/app/dist-electron/main.js:13895:9)
    at async initWaypaperDaemon (/opt/waypaper-engine/resources/app/dist-electron/main.js:13872:7)
    at async /opt/waypaper-engine/resources/app/dist-electron/main.js:15217:3
Could not start wpe-daemon, shutting down app...
/usr/bin/waypaper-engine: line 805: Something went wrong: command not found

> waypaper-engine daemon                                              
starting daemon...
swww is installed in the system
Connection to waypaper daemon established.
Connection to waypaper daemon established.
Connection to waypaper daemon established.
Connection to waypaper daemon established

> waypaper-engine run                                                                    
swww is installed in the system
Error: Failed to establish connection to waypaper daemon.
    at testConnection (/opt/waypaper-engine/resources/app/dist-electron/main.js:13895:9)
    at async initWaypaperDaemon (/opt/waypaper-engine/resources/app/dist-electron/main.js:13872:7)
    at async /opt/waypaper-engine/resources/app/dist-electron/main.js:15217:3
Could not start wpe-daemon, shutting down app...
/usr/bin/waypaper-engine: line 805: Something went wrong: command not found

**Comment by 0bCdian** [comment]
Mmmm, I'm thinking maybe this is related to trying to start a playlists with different monitor configurations from those in the playlists (You mentioned you use clamshell mode), I will try to reproduce this first to see what could be happening.

**Comment by 0bCdian** [comment]
I think I may have found what is causing this, I tried disabling one monitor and resetting the daemon and it leads to crashes, but I am able to run logs. Which version are you using? -git or the normal release? Just to check why wouldn't it let you run it with --logs.

**Comment by aarRJaay** [comment]
Hi - Thank you for your VERY fast reply. I'm on
aur/waypaper-engine-git 2.0.0.r4.dbb8b6d-3 [+0 ~0.00] [Installed: 2.0.3.r1.a8f3a7e-1]

Happy to remove and install another if that's best

[image.png]

I assume either 1 or 2 would be better looking at it as they are newer versions.

----------------------------"No trees were killed to send this message, but a large number of electrons were terribly inconvenienced." - Neil deGrasse Tyson

**Comment by 0bCdian** [comment]
Hmm, it seems you're a few commits behind, if I remember I had a bug in which I didn't put a catch all clause for unhandled exceptions, and so the daemon would sometimes crash before generating logs. Btw, the problem was what I thought, I was throwing on purpose on the event that the swww command fails 3 times, so that's what causing this, I changed that behavior to just stop the playlist on an error. Try the latest git to see if the problem disappears.

**Comment by aarRJaay** [comment]
Downloaded the most recent version and it's all good now. Thank you

----------------------------
"No trees were killed to send this message, but a large number of electrons were terribly inconvenienced." - Neil deGrasse Tyson

Sent from Proton Mail Android

-------- Original Message --------

**Comment by 0bCdian** [comment]
No probs man, always happy to help!
