### ISSUE TITLE
Cannot run CLI options

### ISSUE THREAD

**Issue by dbl-hoo** [0bCdian/Waypaper-Engine#5]
When I try to set a random image, I get an error that the daemon isn't running, even if I have just started the daemon:

[kirkham@endeavour ~]$ pidof wpe-daemon 
56387
[kirkham@endeavour ~]$ waypaper-engine random
/usr/bin/waypaper-engine: line 661: socat: command not found
Seems like the daemon is not running, make sure to run 'waypaper-engine daemon' first
[kirkham@endeavour ~]$

**Comment by 0bCdian** [comment]
Seems like socat is not installed on your system (Kinda weird, I thought it was installed by default on arch) install it and then try to run again it. 

 ```bash 
sudo pacman -S socat
```

**Comment by 0bCdian** [comment]
Since  you haven't responded yet I will close this issue, if you still have any feel free to open a new one.
