### ISSUE TITLE
Wallpapers not changing in portrait orientation

### ISSUE THREAD

**Issue by holydingus** [0bCdian/Waypaper-Engine#59]
Hello, 
I have encountered a problem where the wallpapers apply fine to my primary landscape monitor, but do not want to apply to my secondary portrait monitor. The wallpaper I'm trying to use is in portrait orientation. 

The wallpaper itself is not the problem, because it runs fine on the landscape monitor.
I am using Hyprland.

Thanks in advance

**Comment by Gribovoy29** [comment]
I've rebooted it. Now it does apply...
![image](https://github.com/user-attachments/assets/b5bd4709-d1eb-4986-8d89-e35f5b1636cc)

**Comment by Gribovoy29** [comment]
I think it doesn't see that the monitor is in portrait. 

My hyprland.conf :
monitor = DP-1, 1920x1200, 2560x0, 1, transform, 3

**Comment by 0bCdian** [comment]
Hi, I have confirmed this is not an issue on my part, but on swww itself, change your swww package to the -git version 

```bash 
yay swww-git
```

https://aur.archlinux.org/packages/swww-git

**Comment by Gribovoy29** [comment]
Yes. The problem was the swww. Installed the git version and everything works great. 

Also thank you for making this easy wallpaper app.
