### ISSUE TITLE
Adding a directory only adds 2 images

### ISSUE THREAD

**Issue by ryphon** [0bCdian/Waypaper-Engine#6]
Maybe it's related to my file picker, but for some reason in the last couple days, when I click "Add Images from Directory", and add a directory with some 10-15 images, I'm only getting the first two alphanumerically.

Hyprland, Arch, Kernel 6.7 etc. I honestly don't know what I've changed since it last worked, been doing... a lot of customizations.

Any thoughts? I think it's GTK related, and something about the File Picker, but not sure where to dig in to actually figure out why it broke for wpe.

**Comment by ryphon** [comment]
Love it, thanks. Thought I was going crazy.

**Comment by 0bCdian** [comment]
I found the bug, for some reason fs.readdir and fs.readdirSync are broken while using {recursive:true} in current versions of electron, so I'm going to test further and open an issue there. In the meantime I'm rewriting some of the logic when searching recursively through directories and working around some potential bugs that could arise in certain situations like a subdirectory image having the same name as an image above and so on, I guess that I will be done later today (It's kind late here on CET time) and push a new patch version fixing this issue.

**Comment by 0bCdian** [comment]
Should be in 01d4a335de5eadddbac95686fd03a1bcbceef726 , I will push the new version to the aur, update in a few minutes and let me know if the issue is fixed to close it :)

**Comment by 0bCdian** [comment]
Sorry about that, had to go out and didn't update the aur package, now it should be actually updated!

**Comment by ryphon** [comment]
Yep, that worked! Thanks!
