### ISSUE TITLE
Random img per monitor ?

### ISSUE THREAD

**Issue by dimitrisfasoulas** [0bCdian/Waypaper-Engine#8]
Is there a way to have a different random image per monitor ?

So for example, if I have 3 monitors and I type `waypaper-engine random` I get 3 different images, 1 one each monitor?

And by extension when the playlist is configured to refresh images in a random order, a random image would be loaded on each monitor instead of a random image in all monitors (as it is now)

**Comment by 0bCdian** [comment]
Hi! I'm currently doing a heavy rewrite of all the playlist logic to separate all the playlists per monitor, and this is one feature I'm also working on adding. So rest assured it will be ready in the near future 👍🏾

**Comment by 0bCdian** [comment]
Hi! i wanted to let you know how things are going, here I showcase the progress being made!

https://github.com/0bCdian/Waypaper-Engine/issues/7#issuecomment-2050289649

**Comment by 0bCdian** [comment]
Hi! Im closing this issue since I released a new version that adds this feature, feel free to open another issue if anything else pops up!
