### ISSUE TITLE
Cannot select display

### ISSUE THREAD

**Issue by ChristopherAckerman** [0bCdian/Waypaper-Engine#98]
When I load waypaper-engine, the "select display" button does not work.

Waypaper version 2.0.3
Arch linux
I've attached a picture of the error; I believe the "select display" button should have my actual displays listed. When I click on it,  I get the error message
![2024-12-29-073833_1714x1395_scrot](https://github.com/user-attachments/assets/c123984c-6fb7-44da-90f3-aab5ae10b47b)

`Error occurred in handler for 'getMonitors': Error: Could not query swww at getMonitors (/opt/waypaper-engine/resources/app/dist-electron/main.js:10657:11) at async /opt/waypaper-engine/resources/app/dist-electron/main.js:11805:10 at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:82855)`

**Comment by 0bCdian** [comment]
Ok, can you get me the version of swww you're running and also see if you have installed wl-randr?

```bash
 sudo pacman -Q | grep "swww"
  sudo pacman -Q | grep "wlr-randr"
   sudo pacman -Q | grep "waypaper"
```

**Comment by ChristopherAckerman** [comment]
Sorry, this was a silly mistake on my end. I was running i3 and looking for a wallpaper setter. I didn't realize this required wayland, but I've installed it and everything is working now. Sorry for wasting your time.

**Comment by 0bCdian** [comment]
> Sorry, this was a silly mistake on my end. I was running i3 and looking for a wallpaper setter. I didn't realize this required wayland, but I've installed it and everything is working now. Sorry for wasting your time.

No probs man! And maybe check it out in the future, as I plan to add more "backend" providers for setting wallpapers in the future, to support x11 also.
